### ISSUE TITLE
invalid document fails editor initialization

### ISSUE THREAD

**Issue by antonkast-google** [Open-Reaction-Database/ord-schema#345]
Create an invalid reaction. Load it in the editor. Open JS console. Observe an uncaught exception during init(). I think the exception is thrown somewhere in validateReaction().

Currently this only prevents the call to ready(), which seems to be used only in automated tests. Maybe we need an invalid reaction test case.

```
  | init | @ | reaction.js:51726
-- | -- | -- | --
  | async function (async) |   |  
  | init | @ | reaction.js:51717
  | onload | @ | 0?user=5e2fad6d1c354…a318d3eda9e3bd9f:32


reaction.js:51726 Uncaught (in promise) 
goog.asserts.AssertionError {message: "Assertion failed", reportErrorToServer: true, messagePattern: "Assertion failed", stack: "AssertionError: Assertion failed↵    at new goog.a…er (http://localhost:5000/js/reaction.js:49756:7)"}
message: "Assertion failed"
messagePattern: "Assertion failed"
reportErrorToServer: true
stack: "AssertionError: Assertion failed↵    at new goog.asserts.AssertionError (http://localhost:5000/js/reaction.js:4143:20)↵    at Object.goog.asserts.doAssertFailure_ (http://localhost:5000/js/reaction.js:4224:11)↵    at Object.goog.asserts.assert (http://localhost:5000/js/reaction.js:4255:18)↵    at jspb.BinaryWriter.writeEnum (http://localhost:5000/js/reaction.js:21998:16)↵    at proto.ord.Time.serializeBinaryToWriter (http://localhost:5000/js/reaction.js:27915:12)↵    at jspb.BinaryWriter.writeMessage (http://localhost:5000/js/reaction.js:22053:3)↵    at proto.ord.ReactionInput.serializeBinaryToWriter (http://localhost:5000/js/reaction.js:37869:12)↵    at jspb.BinaryWriter.writeMessage (http://localhost:5000/js/reaction.js:22053:3)↵    at jspb.Map.serializeBinary (http://localhost:5000/js/reaction.js:25737:21)↵    at Function.proto.ord.Reaction.serializeBinaryToWriter (http://localhost:5000/js/reaction.js:49756:7)"
__proto__: goog.debug.Error
`

**Comment by antonkast-google** [comment]
Sorry! There was something wrong with my runtime environment. This does not reproduce when running the editor from a Docker image.
