### ISSUE TITLE
Problem with `mybinder` link

### ISSUE THREAD

**Issue by fwmeng88** [open-reaction-database/ord-schema#622]
Thanks for the impressive work!

I was trying to understand more about `ord-schema`, but it seems that the binder link is broken. The error occurs when the package tries to check `protoc` in *setup.py*. My guess is that the checking happen before the dependencies were installed, which resulted to an error. I am wondering if we can remove the dependency checking in *setup.py*?

[blob:https://mybinder.org/b687a518-c1c6-46ca-87f4-0133f0e2d45c](https://mybinder.org/v2/gh/open-reaction-database/ord-schema/HEAD?filepath=examples)

**Additional information to reproduce the errors**

I have tried with Google Chrome Version 99.0.4844.82 (Official Build) (64-bit) in Fedora 35 and Window 10. Firefox has been also tried.

Thanks for helping!

**Comment by fwmeng88** [comment]
Thanks a lot!

**Comment by skearnes** [comment]
Pasting the full error log:
```
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockermweiekdn'...
HEAD is now at 19cca1c fix safe_join (#621)
Building conda environment for python=Using CondaBuildPack builder
Building conda environment for python=Building conda environment for python=Step 1/51 : FROM buildpack-deps:bionic
 ---> 720c9b132047
Step 2/51 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 1fccd7e2c9a8
Step 3/51 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends locales > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 78a703e420e0
Step 4/51 : RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen &&     locale-gen
 ---> Using cache
 ---> 8dc6339df76a
Step 5/51 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> d4da77f5defd
Step 6/51 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> 031f779b1441
Step 7/51 : ENV LANGUAGE en_US.UTF-8
 ---> Using cache
 ---> 6a1e35a43063
Step 8/51 : ENV SHELL /bin/bash
 ---> Using cache
 ---> b236bbc84020
Step 9/51 : ARG NB_USER
 ---> Using cache
 ---> d01b1d83f14c
Step 10/51 : ARG NB_UID
 ---> Using cache
 ---> f969bfac098d
Step 11/51 : ENV USER ${NB_USER}
 ---> Using cache
 ---> 3f1165e5195d
Step 12/51 : ENV HOME /home/${NB_USER}
 ---> Using cache
 ---> 874fde8af8d9
Step 13/51 : RUN groupadd         --gid ${NB_UID}         ${NB_USER} &&     useradd         --comment "Default user"         --create-home         --gid ${NB_UID}         --no-log-init         --shell /bin/bash         --uid ${NB_UID}         ${NB_USER}
 ---> Using cache
 ---> aebf1cd156f8
Step 14/51 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends        less        unzip        > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> a612ee835eed
Step 15/51 : EXPOSE 8888
 ---> Using cache
 ---> d483ea791074
Step 16/51 : ENV APP_BASE /srv
 ---> Using cache
 ---> cf1642602e46
Step 17/51 : ENV CONDA_DIR ${APP_BASE}/conda
 ---> Using cache
 ---> 67301315c674
Step 18/51 : ENV NB_PYTHON_PREFIX ${CONDA_DIR}/envs/notebook
 ---> Using cache
 ---> 026341b2abfd
Step 19/51 : ENV NPM_DIR ${APP_BASE}/npm
 ---> Using cache
 ---> 43773165bba5
Step 20/51 : ENV NPM_CONFIG_GLOBALCONFIG ${NPM_DIR}/npmrc
 ---> Using cache
 ---> 3e30c9cd5d9a
Step 21/51 : ENV NB_ENVIRONMENT_FILE /tmp/env/environment.lock
 ---> Using cache
 ---> 47d878a5deff
Step 22/51 : ENV MAMBA_ROOT_PREFIX ${CONDA_DIR}
 ---> Using cache
 ---> cdf932d82e2a
Step 23/51 : ENV MAMBA_EXE ${CONDA_DIR}/bin/mamba
 ---> Using cache
 ---> 53a83a4f50cc
Step 24/51 : ENV KERNEL_PYTHON_PREFIX ${NB_PYTHON_PREFIX}
 ---> Using cache
 ---> 26b87b87413a
Step 25/51 : ENV PATH ${NB_PYTHON_PREFIX}/bin:${CONDA_DIR}/bin:${NPM_DIR}/bin:${PATH}
 ---> Using cache
 ---> f068a64f01ea
Step 26/51 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e8-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2factivate-2dconda-2esh-391af5 /etc/profile.d/activate-conda.sh
 ---> Using cache
 ---> e0d6b552b635
Step 27/51 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e8-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2fenvironment-2elock-1dbdca /tmp/env/environment.lock
 ---> Using cache
 ---> a622fad2433c
Step 28/51 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e8-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2finstall-2dbase-2denv-2ebash-8fbb20 /tmp/install-base-env.bash
 ---> Using cache
 ---> b036b89fb8c4
Step 29/51 : RUN TIMEFORMAT='time: %3R' bash -c 'time /tmp/install-base-env.bash' && rm -rf /tmp/install-base-env.bash /tmp/env
 ---> Using cache
 ---> 297d03f9dab9
Step 30/51 : RUN mkdir -p ${NPM_DIR} && chown -R ${NB_USER}:${NB_USER} ${NPM_DIR}
 ---> Using cache
 ---> 81b333c93fce
Step 31/51 : USER root
 ---> Using cache
 ---> 51e3b78c8cf3
Step 32/51 : ARG REPO_DIR=${HOME}
 ---> Using cache
 ---> a60b3b6e0898
Step 33/51 : ENV REPO_DIR ${REPO_DIR}
 ---> Using cache
 ---> 3b16e97ddffa
Step 34/51 : WORKDIR ${REPO_DIR}
 ---> Using cache
 ---> 8b306502b7df
Step 35/51 : RUN chown ${NB_USER}:${NB_USER} ${REPO_DIR}
 ---> Using cache
 ---> 7d4eed0cb794
Step 36/51 : ENV PATH ${HOME}/.local/bin:${REPO_DIR}/.local/bin:${PATH}
 ---> Using cache
 ---> 6c90d818e745
Step 37/51 : ENV CONDA_DEFAULT_ENV ${KERNEL_PYTHON_PREFIX}
 ---> Using cache
 ---> cb78cfac87b0
Step 38/51 : COPY --chown=1000:1000 src/environment.yml ${REPO_DIR}/environment.yml
 ---> Using cache
 ---> 0979281beca9
Step 39/51 : USER ${NB_USER}
 ---> Using cache
 ---> 3282098dd416
Step 40/51 : RUN TIMEFORMAT='time: %3R' bash -c 'time ${MAMBA_EXE} env update -p ${NB_PYTHON_PREFIX} --file "environment.yml" && time ${MAMBA_EXE} clean --all -f -y && ${MAMBA_EXE} list -p ${NB_PYTHON_PREFIX} '
 ---> Running in d782d90fc0e5
pkgs/r/noarch             
pkgs/main/noarch          
rdkit/linux-64            
pkgs/r/linux-64           
rdkit/noarch              
pkgs/main/linux-64        
conda-forge/noarch        
conda-forge/linux-64      
Transaction

  Prefix: /srv/conda/envs/notebook

  Updating specs:

   - rdkit
   - python
   - pip


  Package               Version  Build                 Channel                  Size
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  Install:
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  + blas                    1.0  openblas              pkgs/main/linux-64      46 KB
  + bottleneck            1.3.4  py37hce1f21e_0        pkgs/main/linux-64     126 KB
  + bzip2                 1.0.8  h7b6447c_0            pkgs/main/linux-64      78 KB
  + cairo                1.16.0  hf32fb01_1            pkgs/main/linux-64       1 MB
  + fontconfig           2.13.1  h6c09931_0            pkgs/main/linux-64     250 KB
  + freetype             2.11.0  h70c0345_0            pkgs/main/linux-64     618 KB
  + giflib                5.2.1  h7b6447c_0            pkgs/main/linux-64      78 KB
  + glib                 2.69.1  h4ff587b_1            pkgs/main/linux-64       2 MB
  + jpeg                     9e  h7f8727e_0            pkgs/main/linux-64     240 KB
  + lcms2                  2.12  h3be6417_0            pkgs/main/linux-64     312 KB
  + libboost             1.73.0  h3ff78a5_11           pkgs/main/linux-64      14 MB
  + libgfortran-ng        7.5.0  ha8ba4b0_17           pkgs/main/linux-64      22 KB
  + libgfortran4          7.5.0  ha8ba4b0_17           pkgs/main/linux-64     995 KB
  + libopenblas          0.3.18  hf726d26_0            pkgs/main/linux-64       5 MB
  + libpng               1.6.37  hbc83047_0            pkgs/main/linux-64     278 KB
  + libtiff               4.2.0  h85742a9_0            pkgs/main/linux-64     502 KB
  + libuuid               1.0.3  h7f8727e_2            pkgs/main/linux-64      17 KB
  + libwebp               1.2.2  h55f646e_0            pkgs/main/linux-64      80 KB
  + libwebp-base          1.2.2  h7f8727e_0            pkgs/main/linux-64     440 KB
  + libxcb                 1.14  h7b6447c_0            pkgs/main/linux-64     505 KB
  + libxml2              2.9.12  h03d6c58_0            pkgs/main/linux-64       1 MB
  + lz4-c                 1.9.3  h295c915_1            pkgs/main/linux-64     185 KB
  + numexpr               2.8.1  py37hecfb737_0        pkgs/main/linux-64     124 KB
  + numpy                1.21.5  py37h7a5d4dd_2        pkgs/main/linux-64      10 KB
  + numpy-base           1.21.5  py37hb8be1f0_2        pkgs/main/linux-64       5 MB
  + pandas                1.3.5  py37h8c16a72_0        pkgs/main/linux-64       9 MB
  + pcre                   8.45  h295c915_0            pkgs/main/linux-64     207 KB
  + pillow                9.0.1  py37h22f2fdc_0        pkgs/main/linux-64     652 KB
  + pixman               0.40.0  h7f8727e_1            pkgs/main/linux-64     373 KB
  + py-boost             1.73.0  py37ha9443f7_11       pkgs/main/linux-64     204 KB
  + rdkit           2020.09.1.0  py37hd50e099_1        rdkit/linux-64          26 MB
  + zstd                  1.4.9  haebb681_0            pkgs/main/linux-64     480 KB

  Change:
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  - cffi                 1.15.0  py37h036bc23_0        installed                    
  + cffi                 1.15.0  py37hd667e15_1        pkgs/main/linux-64     222 KB

  Upgrade:
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  - openssl              1.1.1l  h7f98852_0            installed                    
  + openssl              1.1.1n  h7f8727e_0            pkgs/main/linux-64       3 MB
  - python               3.7.12  hb7a2778_100_cpython  installed                    
  + python               3.7.13  h12debd9_0            pkgs/main/linux-64      46 MB
  - sqlite               3.37.0  h9cd32fc_0            installed                    
  + sqlite               3.38.2  hc218d9a_0            pkgs/main/linux-64       1 MB

  Downgrade:
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  - icu                    69.1  h9c3ff4c_0            installed                    
  + icu                    58.2  he6710b0_3            pkgs/main/linux-64      11 MB
  - libffi                3.4.2  h7f98852_5            installed                    
  + libffi                  3.3  he6710b0_2            pkgs/main/linux-64      50 KB
  - nodejs              14.18.3  h8ca31f7_2            installed                    
  + nodejs              10.13.0  he6710b0_0            pkgs/main/linux-64      13 MB

  Summary:

  Install: 32 packages
  Change: 1 packages
  Upgrade: 3 packages
  Downgrade: 3 packages

  Total download: 143 MB

â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€



Looking for: ['python', 'rdkit', 'pip']


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Installing pip dependencies: ...working... [91mPip subprocess error:
  Running command git clone --filter=blob:none -q https://github.com/open-reaction-database/ord-schema /tmp/pip-install-mqh4h8iw/ord-schema_af625c02bb5243578145d176b5884f9a
  ERROR: Command errored out with exit status 1:
   command: /srv/conda/envs/notebook/bin/python /srv/conda/envs/notebook/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmphzilxhba
       cwd: /tmp/pip-install-mqh4h8iw/ord-schema_af625c02bb5243578145d176b5884f9a
  Complete output (49 lines):
  running bdist_wheel
  running build
  running build_py
  Traceback (most recent call last):
    File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 245, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 59, in <module>
      cmdclass={'build_py': BuildPyCommand})
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 136, in run
      self.run_command(cmd_name)
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
      super().run_command(command)
    File "/tmp/pip-build-env-lvu887n3/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "setup.py", line 32, in run
      raise RuntimeError('cannot find protoc')
  RuntimeError: cannot find protoc
  ----------------------------------------
  ERROR: Failed building wheel for ord-schema
ERROR: Could not build wheels for ord-schema, which is required to install pyproject.toml-based projects

[0mRan pip subprocess with arguments:
['/srv/conda/envs/notebook/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/jovyan/condaenv.j6emx4u1.requirements.txt']
Pip subprocess output:
Collecting ord-schema
  Cloning https://github.com/open-reaction-database/ord-schema to /tmp/pip-install-mqh4h8iw/ord-schema_af625c02bb5243578145d176b5884f9a
  Resolved https://github.com/open-reaction-database/ord-schema to commit 19cca1cff81ef121ba05425fcddad1f9ea294fd7
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting absl-py>=0.9.0
  Downloading absl_py-1.0.0-py3-none-any.whl (126 kB)
Collecting flask>=1.1.2
  Downloading Flask-2.1.2-py3-none-any.whl (95 kB)
Requirement already satisfied: numpy>=1.18.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from -r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 3)) (1.21.5)
Collecting numpy>=1.18.1
  Downloading numpy-1.21.6-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
Collecting openpyxl>=3.0.5
  Downloading openpyxl-3.0.9-py2.py3-none-any.whl (242 kB)
Requirement already satisfied: pandas>=1.0.4 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from -r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 5)) (1.3.5)
Collecting protobuf>=3.13.0
  Downloading protobuf-3.20.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
Collecting protoc-wheel-0>=3.14.0
  Downloading protoc_wheel_0-3.20.0-py2.py3-none-manylinux1_x86_64.whl (1.7 MB)
Collecting pygithub>=1.51
  Downloading PyGithub-1.55-py3-none-any.whl (291 kB)
Requirement already satisfied: python-dateutil>=1.10.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from -r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 9)) (2.8.2)
Requirement already satisfied: jinja2>=2.0.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from -r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 10)) (3.0.3)
Collecting jinja2>=2.0.0
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting xlrd<2.0.0
  Downloading xlrd-1.2.0-py2.py3-none-any.whl (103 kB)
Collecting xlwt>=1.3.0
  Downloading xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
Collecting joblib>=1.0.0
  Downloading joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Requirement already satisfied: six in /srv/conda/envs/notebook/lib/python3.7/site-packages (from absl-py>=0.9.0->-r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: importlib-metadata>=3.6.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from flask>=1.1.2->-r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 2)) (4.10.1)
Collecting Werkzeug>=2.0
  Downloading Werkzeug-2.1.2-py3-none-any.whl (224 kB)
Collecting itsdangerous>=2.0
  Downloading itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting click>=8.0
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Requirement already satisfied: pytz>=2017.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas>=1.0.4->-r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 5)) (2021.3)
Collecting deprecated
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied: pyjwt>=2.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pygithub>=1.51->-r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 8)) (2.3.0)
Collecting pynacl>=1.4.0
  Downloading PyNaCl-1.5.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (856 kB)
Requirement already satisfied: requests>=2.14.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pygithub>=1.51->-r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 8)) (2.27.1)
Requirement already satisfied: MarkupSafe>=2.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from jinja2>=2.0.0->-r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 10)) (2.0.1)
Requirement already satisfied: typing-extensions>=3.6.4 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from importlib-metadata>=3.6.0->flask>=1.1.2->-r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 2)) (4.0.1)
Requirement already satisfied: zipp>=0.5 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from importlib-metadata>=3.6.0->flask>=1.1.2->-r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 2)) (3.7.0)
Requirement already satisfied: cffi>=1.4.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pynacl>=1.4.0->pygithub>=1.51->-r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 8)) (1.15.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from requests>=2.14.0->pygithub>=1.51->-r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 8)) (2.0.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from requests>=2.14.0->pygithub>=1.51->-r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 8)) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from requests>=2.14.0->pygithub>=1.51->-r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 8)) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from requests>=2.14.0->pygithub>=1.51->-r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 8)) (3.3)
Collecting wrapt<2,>=1.10
  Downloading wrapt-1.14.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (75 kB)
Requirement already satisfied: pycparser in /srv/conda/envs/notebook/lib/python3.7/site-packages (from cffi>=1.4.1->pynacl>=1.4.0->pygithub>=1.51->-r /home/jovyan/condaenv.j6emx4u1.requirements.txt (line 8)) (2.21)
Building wheels for collected packages: ord-schema
  Building wheel for ord-schema (pyproject.toml): started
  Building wheel for ord-schema (pyproject.toml): finished with status 'error'
Failed to build ord-schema

failed
[91m
CondaEnvException: Pip failed

[0mFinished libffi                               (00m:00s)              50 KB    262 KB/s
Finished pcre                                 (00m:00s)             207 KB    639 KB/s
Finished libxcb                               (00m:00s)             505 KB      1 MB/s
Finished bzip2                                (00m:00s)              78 KB    191 KB/s
Finished openssl                              (00m:00s)               3 MB      6 MB/s
Finished sqlite                               (00m:00s)               1 MB      2 MB/s
Finished zstd                                 (00m:00s)             480 KB    933 KB/s
Finished freetype                             (00m:00s)             618 KB      1 MB/s
Finished libxml2                              (00m:00s)               1 MB      2 MB/s
Finished lcms2                                (00m:00s)             312 KB    470 KB/s
Finished cairo                                (00m:00s)               1 MB      2 MB/s
Finished giflib                               (00m:00s)              78 KB    106 KB/s
Finished pillow                               (00m:00s)             652 KB    840 KB/s
Finished pixman                               (00m:00s)             373 KB    454 KB/s
Finished libuuid                              (00m:00s)              17 KB     20 KB/s
Finished cffi                                 (00m:00s)             222 KB    240 KB/s
Finished icu                                  (00m:01s)              11 MB      8 MB/s
Finished py-boost                             (00m:00s)             204 KB    146 KB/s
Finished bottleneck                           (00m:00s)             126 KB     85 KB/s
Finished libopenblas                          (00m:01s)               5 MB      3 MB/s
Finished libgfortran4                         (00m:00s)             995 KB    501 KB/s
Finished pandas                               (00m:01s)               9 MB      4 MB/s
Finished libtiff                              (00m:00s)             502 KB    228 KB/s
Finished libpng                               (00m:00s)             278 KB    125 KB/s
Finished numpy                                (00m:00s)              10 KB      4 KB/s
Finished lz4-c                                (00m:00s)             185 KB     79 KB/s
Finished glib                                 (00m:00s)               2 MB    752 KB/s
Finished fontconfig                           (00m:00s)             250 KB    104 KB/s
Finished numexpr                              (00m:00s)             124 KB     51 KB/s
Finished blas                                 (00m:00s)              46 KB     19 KB/s
Finished libwebp-base                         (00m:00s)             440 KB    171 KB/s
Finished libwebp                              (00m:00s)              80 KB     31 KB/s
Finished libgfortran-ng                       (00m:00s)              22 KB      8 KB/s
Finished libboost                             (00m:01s)              14 MB      6 MB/s
Finished jpeg                                 (00m:00s)             240 KB     91 KB/s
Finished numpy-base                           (00m:01s)               5 MB      1 MB/s
Finished rdkit                                (00m:02s)              26 MB      5 MB/s
Finished nodejs                               (00m:02s)              13 MB      3 MB/s
Finished python                               (00m:04s)              46 MB      9 MB/s
[91mtime: 62.819
[0mRemoving intermediate container d782d90fc0e5
The command '/bin/sh -c TIMEFORMAT='time: %3R' bash -c 'time ${MAMBA_EXE} env update -p ${NB_PYTHON_PREFIX} --file "environment.yml" && time ${MAMBA_EXE} clean --all -f -y && ${MAMBA_EXE} list -p ${NB_PYTHON_PREFIX} '' returned a non-zero code: 1Built image, launching...
Failed to connect to event stream
```

**Comment by skearnes** [comment]
The problem seems to be that environment.yml is misconfigured; the first `pip` listing shows up as requiring no packages.

**Comment by skearnes** [comment]
Update: that's not it.
> Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

**Comment by skearnes** [comment]
@fwmeng88 please try https://mybinder.org/v2/gh/skearnes/ord-schema/binder --- will be merged soon!

**Comment by FanwangM** [comment]
I can host the interface locally now. 
Thanks for helping! @skearnes
